from __future__ import annotations

FIELD_ALIASES: dict[str, tuple[str, ...]] = {
    "parameter_name": ("parameter_name", "parameter", "kinetic_parameter", "parameter type"),
    "ec_number": ("ec_number", "ec", "ec no", "ec-number"),
    "uniprot": ("uniprot", "uniprot_id", "enzyme_id", "enzyme accession"),
    "enzyme_type": ("enzyme_type", "enzyme type", "wildtype_mutant", "mutation_status", "wt_mut"),
    "mutation": ("mutation", "mutations", "variant", "mutant"),
    "sequence": ("sequence", "aa_sequence", "protein_sequence"),
    "substrate": ("substrate", "substrate_name", "reaction_substrate"),
    "smiles": ("smiles", "substrate_smiles"),
    "organism": ("organism", "species", "host"),
    "commentary": ("commentary", "comment", "condition_note", "notes"),
    "record_id": ("record_id", "formal_record_id", "formal_id", "formal record id"),
    "business_key": ("business_key",),
    "source_record_id": ("source_record_id", "record_id_source", "source_id"),
    "source_release": ("source_release", "source_version"),
    "source_db": ("source_db", "source_database", "database"),
    "sequence_source": ("sequence_source", "seq_source"),
    "parse_status": ("parse_status", "status"),
    "value_normalized": ("value_normalized", "normalized_value", "normalized", "normalized_measurement"),
    "unit_normalized": ("unit_normalized", "normalized_unit", "std_unit"),
    "ph": ("ph", "p_h"),
    "temperature": ("temperature", "temp", "temperature_c"),
    "ions": ("ions", "ion", "cofactor_ions"),
    "reaction_raw": ("reaction_raw", "reaction"),
    "substrate_raw": ("substrate_raw", "substrate_text", "substrate_original"),
    "record_key": ("record_key", "workspace_record_key", "entry_id"),
    "source": ("source", "data_source", "dataset"),
    "source_file": ("source_file", "file", "filename"),
    "source_row": ("source_row", "row", "line_no"),
    "release_id": ("release_id", "version", "release"),
    "enzyme_id": ("enzyme_id", "enzyme", "enzyme accession", "uniprot_id", "uniprot"),
    "condition_type": ("condition_type", "trait_type", "trait", "field_type"),
    "raw_value": ("raw_value", "value", "raw", "measurement"),
    "normalized_value": ("normalized_value", "normalized", "normalized_measurement"),
    "raw_unit": ("raw_unit", "unit", "rawunit"),
    "normalized_unit": ("normalized_unit", "normalized_unit", "std_unit"),
    "quality_flag": ("quality_flag", "flag", "qc_flag"),
    "condition": ("condition", "condition_note", "notes"),
    "species": ("species", "organism"),
    "wildtype_mutant": ("wildtype_mutant", "mutation_status", "mutant", "wt_mut"),
    "value": ("value", "measurement", "trait_value"),
    "unit": ("unit", "measurement_unit"),
}


def normalize_header(name: str) -> str:
    return "".join(ch.lower() for ch in name.strip() if ch.isalnum())
